### ISSUE TITLE
feat: support iso language codes

### ISSUE THREAD

**Issue by dargmuesli** [http-util/status-i18n#27]
The library currently indexes by lowercase BCP 47 locale names. It'd be great if one could use [ISO-639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) like `en` or `de` too! A region information is not common to be used in many languages.

**Comment by dargmuesli** [comment]
Great, thank you <3 That would be "dargmuesli" too.

**Comment by dargmuesli** [comment]
Hey @Kimi-Gao, the required Travis status check never finishes and blocks everything. I have no permission to remove it from being required. Could you please do so?

I'd migrate to GitHub Actions then.

**Comment by Kimi-Gao** [comment]
@dargmuesli Sure, it has been removed. In addition, I grant you the permission as the admin as well.

**Comment by dargmuesli** [comment]
Thank you! :)
